[versions]
agp = "8.13.2"
kotlin = "1.9.0"

coreKtx = "1.12.0"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"

lifecycleRuntimeKtx = "2.6.2"
activityCompose = "1.7.2"

composeBom = "2023.08.00"

constraintlayout = "2.2.0"
navigationCompose = "2.7.3"

room = "2.6.1"

biometricKtx = "1.1.0"

playServicesMaps = "19.0.0"

accompanist = "0.31.3-beta"


[libraries]

# Core

androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }

androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }

androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }


# Compose BOM

androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }


# Compose

androidx-ui = { group = "androidx.compose.ui", name = "ui" }

androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }

androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }

androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }

androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }

androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }

androidx-material3 = { group = "androidx.compose.material3", name = "material3" }

androidx-material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended" }


# Navigation

androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigationCompose" }


# ConstraintLayout

androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }


# Accompanist

accompanist-pager = { group = "com.google.accompanist", name = "accompanist-pager", version.ref = "accompanist" }

accompanist-pager-indicators = { group = "com.google.accompanist", name = "accompanist-pager-indicators", version.ref = "accompanist" }


# Room

androidx-room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }

androidx-room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }

androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }


# Biometric

androidx-biometric-ktx = { group = "androidx.biometric", name = "biometric-ktx", version.ref = "biometricKtx" }


# Google Maps

play-services-maps = { group = "com.google.android.gms", name = "play-services-maps", version.ref = "playServicesMaps" }


# Tests

junit = { group = "junit", name = "junit", version.ref = "junit" }

androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }

androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }


[plugins]

androidApplication = { id = "com.android.application", version.ref = "agp" }

jetbrainsKotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }